# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'listPhoto' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for listPhoto

  target 'listPhotoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'listPhotoUITests' do
    inherit! :search_paths
    # Pods for testing
  end
	pod 'JPush' 
	pod 'AvoidCrash'
 	pod 'Masonry'
	pod 'SDWebImage'
   	pod 'MBProgressHUD'
	pod 'Reachability'
	pod 'RTRootNavigationController'
	pod 'FDFullscreenPopGesture'
	pod 'IQKeyboardManager'
	pod 'AFNetworking'
	pod 'MJRefresh'
	pod 'MJExtension'
    pod 'DZNEmptyDataSet'


end
